version: "3.9"

services:
  backend:
    build: ./backend
    container_name: dolma-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000 --reload
    restart: always

  frontend:
    build: ./frontend
    container_name: dolma-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # 👇 point to host-accessible backend
      - VITE_API_BASE=http://localhost:5000
    depends_on:
      - backend
    restart: always
